defmodule GameNPC.Executor do
  @moduledoc """
  Plan executor for game NPC AI.

  Executes plans generated by the HTN planner, managing state transitions
  and handling failures gracefully.

  ## Usage

      {:ok, plan} = Planner.run(:patrol, facts, traits)
      {:ok, new_state} = Executor.execute_plan(plan, current_state)

  ## Failure Handling

  When a primitive fails:
  1. The executor stops plan execution
  2. Returns `{:error, reason, last_state}`
  3. The caller can attempt replanning with the new state

  """

  alias Operator.HTN.{Plan, Registry}

  @doc """
  Execute a plan to completion or first failure.

  ## Parameters

  - `plan` - The plan to execute
  - `state` - Current actor state (map with position, health, etc.)

  ## Returns

  - `{:ok, final_state}` - All tasks completed successfully
  - `{:error, reason, state}` - A task failed

  ## Examples

      iex> plan = Plan.new(:patrol, [{:move_to, [waypoint]}, {:scan, []}])
      iex> {:ok, new_state} = Executor.execute_plan(plan, initial_state)

  """
  @spec execute_plan(Plan.t(), map()) :: {:ok, map()} | {:error, term(), map()}
  def execute_plan(plan, state) do
    execute_tasks(plan.tasks, state)
  end

  @doc """
  Execute a single task by name.

  Looks up the primitive in the registry and executes its run function.

  ## Parameters

  - `task_name` - Atom name of the primitive
  - `args` - List of arguments for the primitive
  - `state` - Current actor state

  ## Returns

  - `{:ok, new_state}` - Task completed successfully
  - `{:error, reason}` - Task failed

  """
  @spec execute_task(atom(), list(), map()) :: {:ok, map()} | {:error, term()}
  def execute_task(task_name, args, state) do
    registry = Registry.all()

    case Registry.get_primitive(task_name, registry) do
      nil ->
        # Not a primitive - might be an abstract task
        {:error, {:not_primitive, task_name}}

      primitive ->
        execute_primitive(primitive, args, state)
    end
  end

  # Private implementation

  defp execute_tasks([], state), do: {:ok, state}

  defp execute_tasks([{task_name, args} | rest], state) do
    case execute_task(task_name, args, state) do
      {:ok, new_state} ->
        log_task_success(task_name, args)
        execute_tasks(rest, new_state)

      {:error, reason} ->
        log_task_failure(task_name, args, reason)
        {:error, reason, state}
    end
  end

  defp execute_primitive(primitive, args, state) do
    # Get the run function from metadata
    run_fn = get_in(primitive.metadata, [:run])

    if run_fn && is_function(run_fn, 2) do
      # Build facts from current state for the run function
      facts = build_facts_from_state(state)

      # Create actor map (the thing being modified)
      # Include pending_args so primitives can access their arguments
      actor = state
              |> Map.drop([:world, :social])
              |> Map.put(:pending_args, args)

      # Execute the primitive
      case run_fn.(actor, facts) do
        {:ok, new_actor} ->
          # Merge actor changes back into state, removing pending_args
          new_state = state
                      |> Map.merge(new_actor)
                      |> Map.delete(:pending_args)
          {:ok, new_state}

        {:error, reason} ->
          {:error, reason}
      end
    else
      # No run function - just succeed with unchanged state
      {:ok, state}
    end
  end

  defp build_facts_from_state(state) do
    Operator.HTN.Facts.from_perception(%{
      self: Map.take(state, [:health, :ammo, :position, :current_waypoint, :weapon_ready]),
      world: Map.get(state, :world, %{}),
      social: Map.get(state, :social, %{})
    })
  end

  defp log_task_success(task_name, args) do
    IO.puts("[NPC] ✓ #{task_name}#{format_args(args)}")
  end

  defp log_task_failure(task_name, args, reason) do
    IO.puts("[NPC] ✗ #{task_name}#{format_args(args)} - #{inspect(reason)}")
  end

  defp format_args([]), do: ""
  defp format_args(args), do: " #{inspect(args)}"
end
