defmodule Operator.HTN.Registry do
  @moduledoc """
  Central storage for HTN goals, tasks, primitives, and axioms.

  The Registry aggregates all HTN behavior modules into a single lookup table,
  enabling the planner and executor to find definitions by name. It uses
  `persistent_term` for essentially free read access after initialization.

  ## How It Works

  1. **Compile time**: Modules using `Operator.HTN.DSL` define goals/tasks/primitives
  2. **After compile**: The `@after_compile` hook calls `register/1`
  3. **Runtime**: The planner calls `get_goal/2`, `get_primitive/2`, etc.

  ```
  ┌──────────────────┐     ┌──────────────────┐     ┌──────────────────┐
  │  MyBehavior.ex   │     │  EnemyAI.ex      │     │  PatrolBehavior  │
  │  use HTN.DSL     │     │  use HTN.DSL     │     │  use HTN.DSL     │
  └────────┬─────────┘     └────────┬─────────┘     └────────┬─────────┘
           │                        │                        │
           └────────────────────────┼────────────────────────┘
                                    ▼
                         ┌──────────────────────┐
                         │      Registry        │
                         │  (persistent_term)   │
                         │                      │
                         │  goals: %{...}       │
                         │  tasks: %{...}       │
                         │  primitives: %{...}  │
                         │  axioms: %{...}      │
                         └──────────────────────┘
  ```

  ## Auto-Registration

  Modules using `Operator.HTN.DSL` are automatically registered after compilation.
  To disable this (useful for testing):

      use Operator.HTN.DSL, auto_register: false

  ## Manual Registration

      # Register a single module
      Operator.HTN.Registry.register(MyHTNModule)

      # Force refresh from all registered modules
      Operator.HTN.Registry.refresh()

  ## Lookup Functions

      # Get the full registry map
      registry = Registry.all()
      #=> %{goals: %{...}, tasks: %{...}, primitives: %{...}, axioms: %{...}}

      # Get specific items by name
      goal = Registry.get_goal(:acquire_data)
      task = Registry.get_task(:move_to)
      primitive = Registry.get_primitive(:attack)
      axiom = Registry.get_axiom(:enemy_nearby)

      # List all registered names
      Registry.list_goal_names()
      #=> [:patrol, :attack, :flee, :idle]

      # Get statistics
      Registry.stats()
      #=> %{goals: 5, tasks: 12, primitives: 8, axioms: 3}

  ## Testing Considerations

  The Registry uses `persistent_term`, which is global state. For test isolation:

  1. Use `async: false` on test modules that touch the Registry
  2. Call `Registry.reset()` in setup to ensure clean state
  3. Use `Operator.HTN.TestHelpers` for convenient setup functions

      defmodule MyTest do
        use ExUnit.Case, async: false
        import Operator.HTN.TestHelpers

        setup :reset_registry

        setup do
          register_modules([MyBehavior])
          :ok
        end
      end

  ## Performance

  * **Reads**: O(1) via `persistent_term` - essentially free
  * **Writes**: Relatively expensive (copies data), but only happens at registration
  * **Memory**: All registered modules share a single persistent_term entry

  ## See Also

  * `Operator.HTN.DSL` - How modules define HTN structures
  * `Operator.HTN.TestHelpers` - Test utilities including `reset_registry/1`
  * `Operator.HTN.Planner` - Uses Registry to look up goals

  """

  alias Operator.HTN.{Axiom, Task}

  @registry_key {__MODULE__, :registry}
  @modules_key {__MODULE__, :modules}

  @typedoc """
  The registry map containing all HTN definitions.

  ## Fields

  * `:goals` - Map of goal name atoms to goal definitions
  * `:tasks` - Map of task name atoms to `%Task{}` structs
  * `:primitives` - Map of primitive name atoms to `%Task{}` structs
  * `:axioms` - Map of axiom name atoms to `%Axiom{}` structs

  """
  @type registry :: %{goals: map(), tasks: map(), primitives: map(), axioms: map()}

  @doc """
  Returns the merged registry containing all registered definitions.

  This is the primary read function - it returns everything in one map
  for efficient batch access by the planner.

  ## Returns

  A map with `:goals`, `:tasks`, `:primitives`, and `:axioms` keys.

  ## Examples

      registry = Registry.all()
      goal = registry.goals[:patrol]
      primitive = registry.primitives[:fire_weapon]

  """
  @spec all() :: registry()
  def all do
    :persistent_term.get(@registry_key, empty_registry())
  end

  @doc """
  Registers an HTN module and refreshes the merged registry.

  The module must export `__htn__/0`, which is automatically generated by
  `use Operator.HTN.DSL`. This function is typically called automatically
  via `@after_compile`, but can be called manually for dynamic registration.

  ## Parameters

  * `module` - The module atom to register

  ## Returns

  `:ok` on success. Silently succeeds if module doesn't export `__htn__/0`.

  ## Examples

      # Manual registration (usually not needed)
      Operator.HTN.Registry.register(MyGame.CombatBehavior)

      # Verify registration
      Registry.list_goal_names()
      #=> [:attack, :defend, :flee]

  """
  @spec register(module()) :: :ok
  def register(module) when is_atom(module) do
    if function_exported?(module, :__htn__, 0) do
      modules =
        @modules_key
        |> :persistent_term.get(MapSet.new())
        |> MapSet.put(module)

      :persistent_term.put(@modules_key, modules)
      refresh(modules)
    else
      :ok
    end
  end

  @doc """
  Forces a refresh of the registry from registered modules.

  Reloads all module definitions and rebuilds the merged registry. This is
  called automatically by `register/1` but can be called manually if you
  suspect the registry is stale.

  ## Parameters

  * `modules` - Optional module list (defaults to all registered modules)

  ## Returns

  `:ok` after rebuilding the registry.

  """
  @spec refresh(Enum.t()) :: :ok
  def refresh(modules \\ modules()) do
    data =
      modules
      |> Enum.map(&module_registry/1)
      |> merge()

    :persistent_term.put(@registry_key, data)
    :ok
  end

  @doc """
  Resets the registry to empty state.

  Clears all registered modules and definitions. Essential for test isolation
  since the registry uses global `persistent_term` storage.

  ## Returns

  `:ok` after clearing.

  ## Examples

      # In test setup
      setup do
        Operator.HTN.Registry.reset()
        :ok
      end

  ## See Also

  * `Operator.HTN.TestHelpers.reset_registry/1` - ExUnit-friendly wrapper

  """
  @spec reset() :: :ok
  def reset do
    :persistent_term.put(@modules_key, MapSet.new())
    :persistent_term.put(@registry_key, empty_registry())
    :ok
  end

  @doc """
  Returns the list of currently registered modules.

  Useful for debugging or saving/restoring registry state in tests.

  ## Returns

  List of module atoms.

  ## Examples

      Registry.modules()
      #=> [MyGame.CombatBehavior, MyGame.PatrolBehavior]

  """
  @spec modules() :: [module()]
  def modules do
    @modules_key
    |> :persistent_term.get(MapSet.new())
    |> MapSet.to_list()
  end

  @doc """
  Get a goal definition by name.

  Goals are high-level objectives that decompose into task sequences.

  ## Parameters

  * `name` - The goal atom (e.g., `:patrol`, `:attack`)
  * `registry` - Optional registry map (defaults to `all()`)

  ## Returns

  The goal map if found, `nil` otherwise.

  ## Examples

      goal = Registry.get_goal(:infiltrate)
      #=> %{name: :infiltrate, precond: #Function<...>, decompose: [...]}

      Registry.get_goal(:nonexistent)
      #=> nil

  """
  @spec get_goal(atom(), registry()) :: map() | nil
  def get_goal(name, registry \\ all()) do
    Map.get(registry.goals, name)
  end

  @doc """
  Get an abstract task by name.

  Tasks are intermediate steps that decompose into subtasks or primitives.

  ## Parameters

  * `name` - The task atom (e.g., `:move_to`, `:prepare_weapon`)
  * `registry` - Optional registry map (defaults to `all()`)

  ## Returns

  The `%Task{}` struct if found, `nil` otherwise.

  ## Examples

      task = Registry.get_task(:travel_to)
      #=> %Task{name: :travel_to, type: :abstract, ...}

  """
  @spec get_task(atom(), registry()) :: Task.t() | nil
  def get_task(name, registry \\ all()) do
    Map.get(registry.tasks, name)
  end

  @doc """
  Get a primitive by name.

  Primitives are directly executable actions - the leaf nodes of the HTN tree.

  ## Parameters

  * `name` - The primitive atom (e.g., `:attack`, `:wait`, `:move`)
  * `registry` - Optional registry map (defaults to `all()`)

  ## Returns

  The `%Task{}` struct (with `type: :primitive`) if found, `nil` otherwise.

  ## Examples

      primitive = Registry.get_primitive(:fire_weapon)
      #=> %Task{name: :fire_weapon, type: :primitive, metadata: %{run: ...}}

      # Use with Executor
      {:ok, actor} = Executor.execute_primitive(primitive, actor, facts)

  """
  @spec get_primitive(atom(), registry()) :: Task.t() | nil
  def get_primitive(name, registry \\ all()) do
    Map.get(registry.primitives, name)
  end

  @doc """
  Get an axiom by name.

  Axioms are reusable query patterns for preconditions.

  ## Parameters

  * `name` - The axiom atom (e.g., `:enemy_nearby`, `:has_weapon`)
  * `registry` - Optional registry map (defaults to `all()`)

  ## Returns

  The `%Axiom{}` struct if found, `nil` otherwise.

  ## Examples

      axiom = Registry.get_axiom(:enemy_in_range)
      #=> %Axiom{name: :enemy_in_range, query_fn: #Function<...>}

      # Evaluate axiom
      Axiom.evaluate(axiom, facts, max_range: 10)
      #=> true

  """
  @spec get_axiom(atom(), registry()) :: Axiom.t() | nil
  def get_axiom(name, registry \\ all()) do
    Map.get(registry.axioms, name)
  end

  @doc """
  Merge multiple registry fragments into one.

  Used internally to combine definitions from multiple modules. Later entries
  override earlier ones if names conflict.

  ## Parameters

  * `registries` - List of registry maps

  ## Returns

  A single merged registry map.

  """
  @spec merge([map()]) :: registry()
  def merge(registries) do
    Enum.reduce(registries, empty_registry(), fn registry, acc ->
      %{
        goals: Map.merge(acc.goals, registry[:goals] || %{}),
        tasks: Map.merge(acc.tasks, registry[:tasks] || %{}),
        primitives: Map.merge(acc.primitives, registry[:primitives] || %{}),
        axioms: Map.merge(acc.axioms, registry[:axioms] || %{})
      }
    end)
  end

  @doc """
  List all registered goal names.

  ## Returns

  List of goal atom names.

  ## Examples

      Registry.list_goal_names()
      #=> [:patrol, :attack, :flee, :idle]

  """
  @spec list_goal_names() :: [atom()]
  def list_goal_names, do: Map.keys(all().goals)

  @doc """
  List all registered abstract task names.

  ## Returns

  List of task atom names.

  ## Examples

      Registry.list_task_names()
      #=> [:move_to, :prepare_weapon, :find_cover]

  """
  @spec list_task_names() :: [atom()]
  def list_task_names, do: Map.keys(all().tasks)

  @doc """
  List all registered primitive names.

  ## Returns

  List of primitive atom names.

  ## Examples

      Registry.list_primitive_names()
      #=> [:walk, :fire, :reload, :wait]

  """
  @spec list_primitive_names() :: [atom()]
  def list_primitive_names, do: Map.keys(all().primitives)

  @doc """
  List all registered axiom names.

  ## Returns

  List of axiom atom names.

  ## Examples

      Registry.list_axiom_names()
      #=> [:enemy_nearby, :has_ammo, :in_cover]

  """
  @spec list_axiom_names() :: [atom()]
  def list_axiom_names, do: Map.keys(all().axioms)

  @doc """
  Return counts for each category.

  Useful for debugging and monitoring registry state.

  ## Returns

  Map with counts for goals, tasks, primitives, and axioms.

  ## Examples

      Registry.stats()
      #=> %{goals: 5, tasks: 12, primitives: 8, axioms: 3}

  """
  @spec stats() :: %{
          goals: non_neg_integer(),
          tasks: non_neg_integer(),
          primitives: non_neg_integer(),
          axioms: non_neg_integer()
        }
  def stats do
    registry = all()

    %{
      goals: map_size(registry.goals),
      tasks: map_size(registry.tasks),
      primitives: map_size(registry.primitives),
      axioms: map_size(registry.axioms)
    }
  end

  # Private helpers

  defp empty_registry do
    %{goals: %{}, tasks: %{}, primitives: %{}, axioms: %{}}
  end

  defp module_registry(module) do
    case safe_htn(module) do
      {:ok, data} -> normalize_registry(data)
      :error -> empty_registry()
    end
  end

  defp safe_htn(module) do
    case safe_apply(module, :__htn__, []) do
      {:ok, data} -> {:ok, data}
      _ -> :error
    end
  end

  defp safe_apply(module, fun, args) do
    {:ok, apply(module, fun, args)}
  rescue
    _ -> {:error, :rescue}
  catch
    _, _ -> {:error, :catch}
  end

  defp normalize_registry(%{goals: goals, tasks: tasks, primitives: primitives} = data) do
    %{
      goals: map_by_name(goals),
      tasks: map_by_name(tasks),
      primitives: map_by_name(primitives),
      axioms: map_by_name(Map.get(data, :axioms, []))
    }
  end

  defp normalize_registry(_), do: empty_registry()

  defp map_by_name(list) when is_list(list) do
    Enum.into(list, %{}, fn item ->
      name = name_from_item(item)
      data = normalize_runtime_item(item)
      {name, data}
    end)
  end

  defp map_by_name(_), do: %{}

  defp name_from_item(%{name: name}), do: name
  defp name_from_item({name, _}) when is_atom(name), do: name
  defp name_from_item(item), do: item

  defp normalize_runtime_item(%{precond: precond, decompose: decompose} = item) do
    %{
      item
      | precond: maybe_eval_function(precond),
        decompose: normalize_decompose(decompose)
    }
  end

  defp normalize_runtime_item(%{precond: precond} = item) do
    %{item | precond: maybe_eval_function(precond)}
  end

  # Axiom normalization - convert AST to runtime Axiom struct
  defp normalize_runtime_item(%{name: name, query_fn: query_fn_ast} = item)
       when is_tuple(query_fn_ast) do
    query_fn = safe_eval_function(query_fn_ast)
    Axiom.new(name, query_fn, metadata: Map.get(item, :metadata, %{}))
  end

  defp normalize_runtime_item(item) when is_map(item), do: item
  defp normalize_runtime_item(item), do: item

  defp normalize_decompose({:static_tasks, tasks}) do
    # Convert static task list to a function
    fn _facts -> tasks end
  end

  defp normalize_decompose({:fn, _, _} = quoted) do
    # Evaluate quoted function AST
    safe_eval_function(quoted)
  end

  defp normalize_decompose(value), do: value

  defp maybe_eval_function({:fn, _, _} = quoted), do: safe_eval_function(quoted)

  defp maybe_eval_function(funs) when is_list(funs) do
    # List of preconditions - evaluate each and combine into single function
    evaluated = Enum.map(funs, &maybe_eval_function/1)

    fn facts ->
      Enum.all?(evaluated, fn
        fun when is_function(fun, 1) -> fun.(facts)
        _ -> true
      end)
    end
  end

  defp maybe_eval_function(value), do: value

  defp safe_eval_function(quoted) do
    {result, _bindings} = Code.eval_quoted(quoted)
    result
  rescue
    _ -> quoted
  catch
    _, _ -> quoted
  end
end
